#!/usr/bin/env python3
def q1(): print("Do you have a problem")
ans= input("YES or NO")
if ans == "yes":
    q3()
elif ans == "q":
    quit()
else:
    print("That is not an option")
    q1()
ans == "no": 
    q2()
def q2(): print("Then don't worry")
def q3(): print("Can you do something about it")
ans= input("YES or NO")
if ans == "yes" or ans == "no": # this is the correct way to write this out
q2() 
